---
driver:
  name: docker
  hostname: nova.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: <%=ENV['SALT_VERSION'] || 'latest'%>
  require_chef: false
  log_level: error
  formula: nova
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
    - name: keystone
      repo: git
      source: https://github.com/salt-formulas/salt-formula-keystone
    - name: apache
      repo: git
      source: https://github.com/salt-formulas/salt-formula-apache
  state_top:
    base:
      "*":
        - linux.system
        - nova
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - nova
          - release
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_mcp_openstack_<%= ENV['OS_VERSION'] || 'ocata' %>.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'docker-dev-local.docker.mirantis.net/epcim/salt/saltstack-ubuntu-xenial-salt-stable/salt:2018_11_19'%>
      platform: ubuntu

suites:

  - name: compute_cluster
    provisioner:
      pillars-from-files:
        nova.sls: tests/pillar/compute_cluster.sls
      pillars:
        release.sls:
          nova:
            compute:
              version: <%= ENV['OS_VERSION'] || 'ocata' %>

  - name: control_cluster
    provisioner:
      pillars-from-files:
        nova.sls: tests/pillar/control_cluster.sls
      pillars:
        release.sls:
          nova:
            controller:
              version: <%= ENV['OS_VERSION'] || 'ocata' %>


# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
