---
driver:
  name: docker
  hostname: nova.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: <%=ENV['SALT_VERSION'] || 'latest'%>
  require_chef: false
  log_level: error
  formula: nova
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://gerrit.mcp.mirantis.com/salt-formulas/linux
    - name: keystone
      repo: git
      source: https://gerrit.mcp.mirantis.com/salt-formulas/keystone
    - name: apache
      repo: git
      source: https://gerrit.mcp.mirantis.com/salt-formulas/apache
    - name: oslo_templates
      repo: git
      source: https://gerrit.mcp.mirantis.com/salt-formulas/oslo-templates
  state_top:
    base:
      "*":
        - linux.system
        - nova
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - nova
          - release

verifier:
  name: inspec
  sudo: true

docker_images:
  - &xenial-20177 <%=ENV['IMAGE_XENIAL_20177'] || 'docker-dev-local.docker.mirantis.net/epcim/salt/saltstack-ubuntu-xenial-salt-2017.7/salt:2018_11_19'%>
  - &xenial-stable <%=ENV['IMAGE_XENIAL_STABLE'] || 'docker-dev-local.docker.mirantis.net/epcim/salt/saltstack-ubuntu-xenial-salt-stable/salt:2018_11_19'%>

platforms:
  - name: xenial-2017.7
    driver_config:
      image: *xenial-20177
      platform: ubuntu

  - name: xenial-stable
    driver_config:
      image: *xenial-stable
      platform: ubuntu

suites:
<% for os_version in ['mitaka','newton','ocata','pike', 'queens', 'rocky'] %>
  - name: compute_cluster_<%=os_version%>
    provisioner:
      pillars-from-files:
        nova.sls: tests/pillar/compute_cluster.sls
        linux_repo_openstack.sls: tests/pillar/repo_mcp_openstack_<%=os_version%>.sls
      pillars:
        release.sls:
          nova:
            compute:
              version: <%=os_version%>

  - name: control_cluster_<%=os_version%>
    provisioner:
      pillars-from-files:
        nova.sls: tests/pillar/control_cluster.sls
        linux_repo_openstack.sls: tests/pillar/repo_mcp_openstack_<%=os_version%>.sls
      pillars:
        release.sls:
          nova:
            controller:
              version: <%=os_version%>
<% end %>

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
